clone_depth: 50
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  matrix:
    - PYTHON: C:\\Python34
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 32
    - PYTHON: C:\\Python34-x64
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 64
    - PYTHON: C:\\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32
    - PYTHON: C:\\Python35-x64
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 64
    - PYTHON: C:\\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32
    - PYTHON: C:\\Python36-x64
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 64
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          raise "There are newer queued builds for this pull request, skipping build."
        } # credits: JuliaLang developers
install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import sys,platform,struct; print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  - pip install -r requirements-dev.txt
  - python windows.py
  - SET PATH=%PATH%%cd%\apertium-all-dev\bin;
  - "ECHO %PATH%"
build: false
test_script:
  - coverage run -m unittest --verbose --buffer tests
  - coverage report --show-missing --fail-under 85 --include 'apertium/**'
artifacts:
  - path: dist\*
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
