language: python
dist: trusty
cache:
    pip: true
python:
    - '3.4'
    - '3.5'
    - '3.6'
    - 'nightly'
install:
    - travis_retry pip install -r requirements-dev.txt
before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f --allow-unauthenticated install apertium-all-dev
    - sudo apt-get -f --allow-unauthenticated install apertium-nno-nob apertium-es-en
script:
    - flake8 *.py **/*.py
    - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then
        mypy **/*.py --strict --any-exprs-report .mypy_coverage;
        cat .mypy_coverage/any-exprs.txt;
        coverage=$$(tail -1 .mypy_coverage/any-exprs.txt | grep -Eo '[0-9\.]+%' | sed 's/%$$//');
        exit $$(echo "$${coverage} < 96" | bc -l);
      fi
    - python -m unittest tests
    - coverage report --fail-under 90
after_success:
    - coveralls
notifications:
    on_failure: change
    on_success: change
